export const APP_LOAD_DOC = "APP_LOAD_DOC",
  APP_DOCUMENT_READ_ERROR = "APP_DOCUMENT_READ_ERROR",
  APP_LOAD_DEFAULT_DOC = "APP_LOAD_DEFAULT_DOC",
  APP_REQUEST_FOCUSED_DOCUMENT = "APP_REQUEST_FOCUSED_DOCUMENT",
  APP_RETURN_FOCUSED_DOCUMENT = "APP_RETURN_FOCUSED_DOCUMENT",
  PING = "PING",
  PONG = "PONG";
